### ISSUE TITLE
Add 5 New NPC Name-Quote Entity To Enrichen The NPC-Quotes Library

### ISSUE THREAD

**Issue by seferciogluecce** [cemuka/NPC-Quotes#1]
Let's Enrichen The NPC-Quotes Library by adding more NPCs with names and quotes.

Add 5 new NPC **Entity** to list of **_entities** in the following format;
```
    private static List<Entity> _entities = new List<Entity>()
    {
        new Entity("Ned",           "Winter is coming..."),
        new Entity("Goblin",        "Time is money my friend."),
        new Entity("Druid",         "I'm awake... I'm awake."),
        //--Your Contribution Starts From Here--
        new Entity("NPC_Name_1",         "NPC_Quote_1"),        
        new Entity("NPC_Name_2",         "NPC_Quote_2"),        
        new Entity("NPC_Name_3",         "NPC_Quote_3"),
        new Entity("NPC_Name_4",         "NPC_Quote_4"),
        new Entity("NPC_Name_5",         "NPC_Quote_5")
    };
```

Requirements:
- Names are allowed to be duplicate but **no duplicate quotes**!
- No duplicate or similar entities to already existing ones! 
- Be cautious of noncharacteristic grammar mistakes!
- Enjoy creating new NPCs!

**Comment by majorb84** [comment]
This appears to have be complete after this [PR](https://github.com/cemuka/NPC-Quotes/pull/2)?

**Comment by seferciogluecce** [comment]
Hi! This issue will stay open through the Hacktoberfest. Feel free to contribute :)

**Comment by reenine99** [comment]
#28

**Comment by TarynMcMillan** [comment]
Is this issue still open?

**Comment by cemuka** [comment]
Yes and happy hacktoberfest :)
